accounts/urls.py
from django.conf import settings
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('social/signup/', views.MySignupView.as_view(), name='signup'),
]

api_v1/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'api_v1'
urlpatterns = [
    path('passhint/', views.passhint.as_view(), name='passhint'),
]

passhint/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'passhint'
urlpatterns = [
    path('search/', views.site_search, name='site_search'),

    path('autocomplete/', views.autocomplete, name='autocomplete'),
    
    path('inline-pw-check/<str:site_name>/', views.inline_pw_check, name='inline_pw_check'),

    path('<str:site_name>/', views.site_detail, name='site_detail'),
]

accounts/models.py
from django.db import models
from django.db.models import F
from django.contrib.auth.models import User
from django.conf import settings

from passhint.common import POINT_DICT
from log.models import LogPoint


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    point = models.BigIntegerField(default=0)

    def set_point(self, key):
        # POINT 부여
        self.point = F('point') + POINT_DICT[key]
        self.save()
        self.refresh_from_db()

        # LOG 저장
        LogPoint.save_log_point(self.user, POINT_DICT[key], key)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import Profile

class SignupForm(UserCreationForm):
    phone_number = forms.CharField()
    address = forms.CharField()

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)

    def save(self):
        user = super().save()
        profile = Profile.objects.create(
            user = user,
            phone_number = self.cleaned_data['phone_number'],
            address = self.cleaned_data['address'])
        return user

class t_SignupForm(forms.Form):
    # phone_number = forms.CharField()
    # address = forms.CharField()

    def signup(self, request, user):
        user.save()
        profile = Profile.objects.create(
            user = user)

class LoginForm(AuthenticationForm):
    answer = forms.IntegerField(label='3+3=?')

    def clean_answer(self):
        answer = self.cleaned_data.get('answer', None)
        if answer != 6:
            raise forms.ValidationError('mismatched!')
        return answer

accounts/views.py
# accounts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login as auth_login
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import get_user_model

from allauth.socialaccount.models import SocialApp
from allauth.socialaccount.views import SignupView
from allauth.socialaccount.templatetags.socialaccount import get_providers

from .forms import SignupForm, LoginForm, t_SignupForm
from report.models import ReportRuleSet, ReportSite


class MySignupView(SignupView):
    template_name = ('accounts/signup_form.html')


def set_report_class(report_list):
    for report in report_list:
        if report.status == 'approved':
            setattr(report, 'class', 'list-group-item-primary')
        elif report.status == 'rejected':
            setattr(report, 'class', 'list-group-item-danger')
        elif report.status == 'late':
            setattr(report, 'class', 'list-group-item-warning')
        else:
            setattr(report, 'class', '')
    
    return report_list

# TODO 본인일 떄 체크해서 정보 수정 메뉴 보여주기
@login_required
def profile(request, username):

    user = get_object_or_404(get_user_model(), username=username)

    report_rulesets = ReportRuleSet.objects.filter(user=user)
    
    # 제보한 RuleSet 별로 승인 상태를 보여주기 위해 class 속성 설정
    report_rulesets = set_report_class(report_rulesets)

    report_sites = ReportSite.objects.filter(user=user)

    # 제보한 Site 별로 승인 상태를 보여주기 위해 class 속성 설정
    report_sites = set_report_class(report_sites)

    return render(request, 'accounts/profile.html', {
            'user' : user,
            'report_rulesets' : report_rulesets,
            'report_sites' : report_sites
        })


def login(request):
    providers = []
    for provider in get_providers():
        try:
            provider.social_app = SocialApp.objects.get(provider=provider.id, sites=settings.SITE_ID)
        except SocialApp.DoesNotExist:
            provider.social_app = None
        providers.append(provider)

    return auth_login(request,
        authentication_form=LoginForm,
        template_name='accounts/login_form.html',
        extra_context={'providers': providers})

accounts/templates/accounts/layout.html
{% extends "layout.html" %}
{% block content %}
<div class="container mt-5">
    {% block accounts_content %} {% endblock %}

    {% include "footer.html" %}
</div>
{% endblock %}

accounts/templates/accounts/login_form.html
{% extends "accounts/layout.html" %}
{% load socialaccount %}
{% load i18n %}
{% block title %}Login | passhint{% endblock title %}
{% block accounts_content %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <div class="card">
            <div class="card-header text-center">
                <h4>{% trans "Social Login" %}</h4>
            </div>
            <div class="card-body text-center">
                {% for provider in providers %}
                    {% if provider.social_app %}
                    <div class="m-4">
                        <a href="{% provider_login_url provider.id %}">
                            <button type="button" class="btn btn-info btn-lg btn-block">{{ provider.name }} login</button>
                        </a>
                    </div>
                    {% else %}
                    <div class="m-4">
                        <button type="button" class="btn btn-secondary btn-lg btn-block">{{ provider.name }}(Disabled)</button>
                    </div>
                    {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}
{% load i18n %}
{% block title %}Profile | passhint{% endblock title %}
{% block accounts_content %}
<div class="row">
    <div class="col-lg-4 order-lg-2">
        <!-- user info -->
        <h4 class="mb-3">
            {% trans "User Information" %}
        </h4>
        <ul class="list-group mb-3">
            <li class="list-group-item">
                <div>
                    <h6 class="my-0"><strong>{% trans "Username" %}</strong></h6>
                    <span>{{ user.get_username|default:"No Username" }}</span>
                </div>
            </li>
            <li class="list-group-item">
                <div>
                    <h6 class="my-0"><strong>{% trans "Email" %}</strong></h6>
                    <span>{{ user.email|default:"No Email" }}</span>
                </div>
            </li>
            <li class="list-group-item">
                <div>
                    <h6 class="my-0"><strong>{% trans "Point" %}</strong></h6>
                    <span>{{ user.profile.point }}</span>
                </div>
            </li>
            <li class="list-group-item">
                <div>
                    <h6 class="my-0"><strong>{% trans "Joined at" %}</strong></h6>
                    <span>{{ user.date_joined }}</span>
                </div>
            </li>
        </ul>
    </div>
    <div class="col-lg-8 order-lg-1 mb-4 mt-4 mt-lg-0">
        <div class="mb-3">
            <h2>{% trans "passhinter history" %}</h2>
        </div>

        <hr>

        <div class="mb-4">
            <h4>{% trans "passhint report" %}</h4>
        </div>
        {% if report_rulesets %}
            <ul class="list-group">
                {% for report_ruleset in report_rulesets %}
                    <li class="list-group-item d-flex justify-content-between {{ report_ruleset.class }}">
                        <div>
                            <h5 class="my-0">
                                <a href="{% url "passhint:site_detail" report_ruleset.site.name %}" 
                                    class="text-info">
                                    {{ report_ruleset.site.name }}
                                </a>
                            </h5>
                            <small class="text-muted">{{ report_ruleset.created_at }}</small>
                        </div>
                        <span class="text-muted">{{ report_ruleset.status }}</span>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <li class="list-group-item">
                <div class="text-center">
                    <h5>{% trans "No history yet" %}</h5>
                </div>
            </li>
        {% endif %}

        <div class="my-4">
            <h4>{% trans "Site report" %}</h4>
        </div>
        {% if report_sites %}
            <ul class="list-group">
                {% for report_site in report_sites %}
                    <li class="list-group-item d-flex justify-content-between {{ report_site.class }}">
                        <div>
                            <h5 class="my-0"><span class="text-info">{{ report_site.name }}</span> <small class="text-muted font-italic">{{ report_site.main_url }}</small class="text-muted font-italic"></h5>
                            <small class="text-muted">{{ report_site.created_at }}</small>
                        </div>
                        <span class="text-muted">{{ report_site.status }}</span>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <li class="list-group-item">
                <div class="text-center">
                    <h5>{% trans "No history yet" %}</h5>
                </div>
            </li>
        {% endif %}

    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}
{% load widget_tweaks%}
{% load i18n %}
{% block title %}Signup | passhint{% endblock title %}
{% block accounts_content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-header text-center">
                <h4>{% trans "Enter your additional information to complete signup" %}</h4>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %} 
                    
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                    {% endfor %}
                    <!-- hidden fields는 위젯만 렌더링 -->
                    {% for field in form.hidden_fields %}
                    {{ field }} 
                    {% endfor %}
                    <!-- visible fields는 모든 요소 렌더링 -->
                    {% for field in form.visible_fields %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-md-9">
                            {{ field|add_class:'form-control' }}
                            <p class="help-block">{{ field.help_text }}</p>
                            {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ error }}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="text-right">
                        <input type="submit" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="card-footer text-muted text-center">
                {% trans "Email is Optional" %}
            </div>
        </div>
    </div>
</div>

{% endblock %}