api_v1/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'api_v1'
urlpatterns = [
    path('passhint/', views.passhint.as_view(), name='passhint'),
]

passhint/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'passhint'
urlpatterns = [
    path('search/', views.site_search, name='site_search'),

    path('autocomplete/', views.autocomplete, name='autocomplete'),
    
    path('inline-pw-check/<str:site_name>/', views.inline_pw_check, name='inline_pw_check'),

    path('<str:site_name>/', views.site_detail, name='site_detail'),
]

report/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'report'
urlpatterns = [
    path('', views.report_site, name='report_site'),
    path('<str:site_name>/',
         views.report_ruleset, name='report_ruleset'),
]

passhint/models.py
from django.db import models
from django.conf import settings
from django.forms import URLField
from django.utils.text import slugify
from django.forms import ValidationError
from django.utils import timezone
from django.db.models import F

import datetime

def url_validator(url):

    url_form_field = URLField()
    try:
        url = url_form_field.clean(url)
    except ValidationError:
        raise ValidationError('Invalid URL Type')

STATUS_CHOICES = (
        ('waiting', 'waiting'),
        ('approved', 'approved'),
        ('rejected', 'rejected'),
        ('late', 'late'),
    )

class TimeStampedModel(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Site(TimeStampedModel):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=60)
    tag = models.CharField(max_length=200, blank=True, null=True)

    hit = models.BigIntegerField(default=0)
    main_url = models.CharField(max_length=100, validators=[url_validator])

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        
        self.name = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    @property
    def get_recent_ruleset(self):
        return self.rule_sets.first()

    @property
    def get_tag_list(self):
        return self.tag.split(',')

    @classmethod
    def get_site_by_tag(cls, keyword):
        '''
        input : keyword
        output : site (single)
        태그가 완전 일치하는 사이트가 하나 존재하면 site 리턴
        존재하지 않거나 복수 존재하면 None 리턴 -> 단 하나가 필요하므로 복수 존재해도 None 리턴
        '''
        sites = cls.objects.all()
        
        result = []
        for site in sites:
            tag_list = site.get_tag_list
            if keyword in tag_list:
                result.append(site)

        if len(result) == 1:
            return result[0]
        else:
            return None

    # hit += 1
    def set_hit_plus_1(self):
        self.hit = F('hit') + 1
        self.save()
        self.refresh_from_db()

    @classmethod
    def search_by_url(cls, url):
        '''
        input : url
        output : list of sites

        1. remove first http(s):// part if exist
        2. remove www. part if exist
        3. split by "."
        4. search Site with tag
        5. if some part of url and Site's tag are same, put that site in results
        '''

        url_list = url.split('//')
        # http(s):// 부분이 존재한다면
        if len(url_list) > 1:
            # 버리고 뒤쪽만 남기기
            url = ''.join(url_list[1:])

        # 맨 앞이 www. 이라면 제거하기
        if url[:4] == 'www.':
            url = url[4:]

        if Site.objects.filter(main_url__icontains=url).exists():
            return Site.objects.filter(main_url__icontains=url)

        # . 을 기준으로 split 후 앞부터 돌면서 검사
        keyword_list = url.split(".")

        results = []
        for keyword in keyword_list:
            site = Site.get_site_by_tag(keyword)
            if site:
                results.append(site)

        return results


class Rule(TimeStampedModel):

    LEVEL_CHOICES = (
        ('success', 'success'),
        ('info', 'info'),
        ('warning', 'warning'),
        ('danger', 'danger'),
    )

    name = models.CharField(max_length=50, unique=True)
    regex = models.CharField(max_length=200, blank=True, null=True)
    regex_result = models.NullBooleanField()
    desc_ko = models.CharField(max_length=200)
    desc_en = models.CharField(max_length=200)
    desc_short = models.CharField(max_length=200)
    error_ko = models.CharField(max_length=200)
    error_en = models.CharField(max_length=200)
    guide_ko = models.CharField(max_length=200)
    guide_en = models.CharField(max_length=200)
    level = models.CharField(max_length=15, choices=LEVEL_CHOICES)

    class Meta:
        ordering = ['-name']

    def __str__(self):
        return '{}-{}'.format(self.name, self.desc_short)

    @classmethod
    def get_rule_by_name(cls, rule_name):
        '''
        input : rule name
        output : rule
        '''
        try:
            rule = cls.objects.get(name=rule_name)

        except cls.DoesNotExist: # len_min_x 일 수 있으므로 확인
            
            rule_div = rule_name.split('_')

            if len(rule_div) == 3 and rule_div[0] == 'len':
                rule_name = '_'.join(rule_div[:2])

                try:
                    rule = cls.objects.get(name=rule_name)
                    rule_len = rule_div[2]

                    rule.regex = rule.regex.replace('{len}', rule_len)
                    rule.desc_ko = rule.desc_ko.replace('{len}', rule_len)
                    rule.desc_en = rule.desc_en.replace('{len}', rule_len)
                    rule.desc_short = rule.desc_short.replace('{len}', rule_len)
                    rule.error_ko = rule.error_ko.replace('{len}', rule_len)
                    rule.error_en = rule.error_en.replace('{len}', rule_len)

                except cls.DoesNotExist:
                    return None
            else:
                return None

        return rule

# XXX RULE SENSITIVE
class BaseRuleSet(models.Model):

    len_min = models.SmallIntegerField(blank=True, null=True)
    len_max = models.SmallIntegerField(blank=True, null=True)
    
    exc_special = models.BooleanField(default=False)
    exc_space = models.BooleanField(default=False)
    exc_id = models.BooleanField(default=False)
    exc_same = models.BooleanField(default=False)
    exc_series = models.BooleanField(default=False)
    exc_common = models.BooleanField(default=False)
    
    inc_2_of_letter_num_special = models.BooleanField(default=False)
    inc_special = models.BooleanField(default=False)
    inc_lower = models.BooleanField(default=False)
    inc_upper = models.BooleanField(default=False)
    inc_number = models.BooleanField(default=False)
    inc_letter = models.BooleanField(default=False)

    class Meta:
        abstract = True

# XXX RULE SENSITIVE
class RuleSet(TimeStampedModel, BaseRuleSet):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, related_name='rule_sets')

    def __str__(self):
        return '{}-{}'.format(self.site, self.created_at)

    class Meta:
        ordering = ['-created_at']

    @property
    def get_true_rule_list(self):
        
        result = []
        
        if self.len_min is not None:
            result.append('len_min_'+str(self.len_min))
        
        if self.len_max is not None:
            result.append('len_max_'+str(self.len_max))
        
        if self.exc_special is True:
            result.append('exc_special')

        if self.exc_space is True:
            result.append('exc_space')
        
        if self.exc_id is True:
            result.append('exc_id')
        
        if self.exc_same is True:
            result.append('exc_same')
        
        if self.exc_series is True:
            result.append('exc_series')
        
        if self.exc_common is True:
            result.append('exc_common')

        if self.inc_2_of_letter_num_special is True:
            result.append('inc_2_of_letter_num_special')
        
        if self.inc_special is True:
            result.append('inc_special')
        
        if self.inc_lower is True:
            result.append('inc_lower')
        
        if self.inc_upper is True:
            result.append('inc_upper')
        
        if self.inc_number is True:
            result.append('inc_number')
        
        if self.inc_letter is True:
            result.append('inc_letter')
        
        return result

passhint/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify

class SiteSearchForm(forms.Form):

    keyword = forms.CharField(
        max_length=30, 
        widget=forms.TextInput(
            attrs={'id':'search_name'}
            )
        )

    def clean_keyword(self):
        keyword = self.cleaned_data.get('keyword').strip()
        return slugify(keyword, allow_unicode=True)

class InlinePwCheckForm(forms.Form):

    pw = forms.CharField(
        max_length=50, 
        widget=forms.PasswordInput(
            attrs={
                'placeholder': _('Check if you can use your password in this site.'),
                'id':'inline_pw_check'
                }
            )
        )

passhint/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, Http404, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.db.models import F, Q, Count
from django.urls import reverse
from django.contrib import messages

import json

from .models import Site, Rule, RuleSet
from .forms import SiteSearchForm, InlinePwCheckForm
from .utils import pw_check
from log.models import LogSearch, LogSite
from accounts.models import Profile


def get_user_or_none(user):
    return user if user.is_authenticated else None

# 메인 페이지
# 서비스 이름으로 passhint 를 검색하고
# 입력에 따라 auto complete를 도와주기
# 우측에 인기 검색어를 보여주기
def main(request):
    
    if request.method == 'POST':
    
        form = SiteSearchForm(request.POST)

        if form.is_valid():

            user = get_user_or_none(request.user)

            keyword = form.cleaned_data.get('keyword')
            try:
                site = Site.objects.get(name=keyword)
            except Site.DoesNotExist: 
                # name 으로 일치되는 것이 없으면 태그에서 완전일치 하는 것이 있는지 검사
                found_site = Site.get_site_by_tag(keyword)
                
                if found_site is None: # 태그로 완전일치가 없거나 다수 존재하면 search 로 이동
                    return HttpResponseRedirect(reverse('passhint:site_search') + '?q='+keyword)
                else: # 완전 일치하는 것이 딱 하나 존재하면 detail 로 이동
                    # 로그 저장
                    LogSearch.save_log_search(user, keyword, found_site.name)
                    return redirect('passhint:site_detail', site_name=found_site.name)
            else:
                # name 일치 존재
                # 로그 저장
                LogSearch.save_log_search(user, keyword, site.name)
                return redirect('passhint:site_detail', site_name=keyword)

    else:    
        form = SiteSearchForm()


    MAIN_ITEM_NUMBER = 7

    # hit 기준 정렬
    all_time_ranking = Site.objects.all().order_by('-hit')[:MAIN_ITEM_NUMBER]

    # log 모델 필요
    this_weak_ranking = LogSite.get_sorted_site_recent_nday(7)[:MAIN_ITEM_NUMBER]
    # today_ranking
    
    # created at 기준 정렬
    new_site_list = Site.objects.all().order_by('name')[:MAIN_ITEM_NUMBER]
    
    # log created at 기준 정렬
    # recent_search_list

    # hit 기준 정렬
    best_passhinter = Profile.objects.all().order_by('-point')[:MAIN_ITEM_NUMBER]

    return render(request, 'passhint/main.html', {
        'form' : form,
        'nav_main' : 'active',
        'all_time_ranking' : all_time_ranking,
        'this_weak_ranking' : this_weak_ranking,
        'new_site_list' : new_site_list,
        'best_passhinter' : best_passhinter,
    })


def site_search(request):
        
    keyword = request.GET.get('q')
    ordey_by = request.GET.get('ordey_by', 'name')

    if keyword:
        # TODO 검색 방식
        # 현재 : 태그 icontain 검색
        sites = Site.objects.filter(Q(tag__icontains = keyword)).prefetch_related('rule_sets').order_by(ordey_by)

        # 로그 저장
        user = get_user_or_none(request.user)
        site_name_list = [site.name for site in sites]
        LogSearch.save_log_search(user, keyword, ','.join(site_name_list))
    else:
        keyword = 'All site'
        sites = Site.objects.all().prefetch_related('rule_sets').order_by(ordey_by)

    
    return render(request, 'passhint/site_search.html', {
        'keyword' : keyword,
        'sites' : sites,
        'nav_site_search' : 'active',
    })


def site_detail(request, site_name):
    
    site = get_object_or_404(Site.objects.prefetch_related('rule_sets').select_related('user'), name=site_name)
    
    # hit++
    site.set_hit_plus_1()

    # 로그 저장
    user = get_user_or_none(request.user)
    LogSite.save_log_site(site, user)

    rules = Rule.objects.all()

    form = InlinePwCheckForm()

    return render(request, 'passhint/site_detail.html', {
        'site' : site,
        'rules' : rules,
        'form' : form,
        })

@csrf_exempt
def autocomplete(request):
    
    q = request.GET.get('term', '')

    # 서비스 중 인 site 중 검색하여 name으로 group_by 한 후 name 만 사용한다
    sites = Site.objects.filter(Q(tag__icontains = q)).order_by('name')

    results = [site.name for site in sites]
    
    return JsonResponse(results, safe=False)


def inline_pw_check(request, site_name):
    if request.method == 'POST':
        form = InlinePwCheckForm(request.POST)
        if form.is_valid():
            pw = request.POST.get('pw')

            if pw:
                try:
                    site = Site.objects.get(name=site_name)
                    rule_list = site.get_recent_ruleset.get_true_rule_list
                except:
                    return JsonResponse({'result' : 'error'}, status=404)
                
                result, message = pw_check(pw, rule_list)
                return JsonResponse({'result' : result, 'message' : message})
                
    return JsonResponse({'result' : 'error'}, status=400)

passhint/templates/passhint/layout.html
{% extends "layout.html" %}
{% block content %}
<div class="container mt-5">
    {% block passhint_content %} {% endblock %}
    {% include "footer.html" %}
</div>
{% endblock %}

passhint/templates/passhint/main.html
{% extends "passhint/layout.html" %}
{% load i18n %}
{% load static %}
{% block passhint_content %}
    <div class="text-center my-5">
        <h1 class="display-4">passhint</h1>
    </div>

    <div class="offset-md-3 col-md-6">
        <form class="form-inline text-center" method="post">
            {% csrf_token %}
            <input type="text" name="keyword" class="form-control" id="search_name" placeholder="Search" aria-label="Search" maxlength="30"
                required style="width: 90%;">
            <button type="submit" class="my-button" style="width: 10%;">
                <i class="material-icons" style="line-height: unset;">search</i>
            </button>
        </form>
    </div>

    <div class="card-deck mt-5">
        <div class="card mb-4 box-shadow">
            <div class="card-header text-center">
                <h5 class="my-0 font-weight-normal">{% trans "All-time ranking" %}</h5>
            </div>
            <div class="card-body px-3 py-0">
                <ul class="list-group list-group-flush">
                    {% for site in all_time_ranking %}
                        <li class="list-group-item text-truncate">
                                {{ forloop.counter }}. <a class="text-info" href="{% url "passhint:site_detail" site.name %}">{{site.name}}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="card mb-4 box-shadow">
            <div class="card-header text-center">
                <h5 class="my-0 font-weight-normal">{% trans "This weak ranking" %}</h5>
            </div>
            <div class="card-body px-3 py-0">
                <ul class="list-group list-group-flush">
                    {% for site_name in this_weak_ranking %}
                    <li class="list-group-item text-truncate">
                        {{ forloop.counter }}.
                        <a class="text-info" href="{% url "passhint:site_detail" site_name %}">{{site_name}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="card mb-4 box-shadow">
            <div class="card-header text-center">
                <h5 class="my-0 font-weight-normal">{% trans "New site" %}</h5>
            </div>
            <div class="card-body px-3 py-0">
                <ul class="list-group list-group-flush">
                    {% for site in new_site_list %}
                    <li class="list-group-item text-truncate">
                        {{ forloop.counter }}.
                        <a class="text-info" href="{% url "passhint:site_detail" site.name %}">{{site.name}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="card mb-4 box-shadow">
            <div class="card-header text-center">
                <h5 class="my-0 font-weight-normal">{% trans "Best passhinter" %}</h5>
            </div>
            <div class="card-body px-3 py-0">
                <ul class="list-group list-group-flush">
                    {% for passhinter in best_passhinter %}
                    <li class="list-group-item text-truncate">
                        {{ forloop.counter }}.
                        <a class="text-info" href="{% url "profile" passhinter.user.username %}">{{passhinter.user.username}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    
    {% include "main_carousel.html" %}
<!-- 
    <hr class="my-5">
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">First featurette heading.
                <span class="text-muted">It'll blow your mind.</span>
            </h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo
                cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" style="width: 500px; height: 500px;"
                src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22500%22%20height%3D%22500%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20500%20500%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1619e346c94%20text%20%7B%20fill%3A%23AAAAAA%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A25pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1619e346c94%22%3E%3Crect%20width%3D%22500%22%20height%3D%22500%22%20fill%3D%22%23EEEEEE%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22185.1328125%22%20y%3D%22261.278125%22%3E500x500%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                data-holder-rendered="true">
        </div>
    </div>

    <hr class="my-5">
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">First featurette heading.
                <span class="text-muted">It'll blow your mind.</span>
            </h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo
                cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" style="width: 500px; height: 500px;"
                src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22500%22%20height%3D%22500%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20500%20500%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1619e346c94%20text%20%7B%20fill%3A%23AAAAAA%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A25pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1619e346c94%22%3E%3Crect%20width%3D%22500%22%20height%3D%22500%22%20fill%3D%22%23EEEEEE%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22185.1328125%22%20y%3D%22261.278125%22%3E500x500%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                data-holder-rendered="true">
        </div>
    </div>
        -->
    <script>
        window.onload = function () {
            var input = document.getElementById("search_name").focus();
        }
    </script>
{% endblock passhint_content %}

passhint/templates/passhint/site_detail.html
{% extends "passhint/layout.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load passhint_extras %}
{% block title %}{{ site.name }} | passhint{% endblock title %}
{% block passhint_content %}
{% get_current_language as LANGUAGE_CODE %}
<div class="row">
    <div class="col-lg-8">
        <!-- passhint info -->
        <h1 class="display-4 site-name">
            {{ site.name }}
        </h1>
        <p>
            {{ site.main_url|get_anchor_tag }}
        </p>
        
        <hr class="my-4">
        <h3 class="px-2">passhint</h3>
        
        {% if site.get_recent_ruleset %}
         
            {% get_html_rule site.get_recent_ruleset.get_true_rule_list LANGUAGE_CODE %}
        
            
            <div class="text-right">
                <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#rule_guide_modal">
                    {% trans "Rule Guide" %}
                </button>
            </div>

            {% include "passhint/site_detail_guide_modal.html" with rules=rules %}
            
        {% else %}
            <h4>{% trans "No passhint yet. Chance to be the first passhinter" %}</h4>
        {% endif %}

        <hr class="my-4">
        <h3 class="px-2">{% trans "In-line password check" %}</h3>
        
        <form id="inline-pw-check" data-url="{% url "passhint:inline_pw_check" site.name %}" method="post" onsubmit="return false;">
            {% csrf_token %} 

            <div class="form-group">
                <div>
                    <div>
                        {{ form.pw|add_class:'form-control' }}
                    </div>
                    <div id="inline-pw-check-error" class="border my-3">
                        <div class="alert alert-light m-0" role="alert">
                            {% trans "Result will be printed here. Don't worry, we never abuse your password" %}
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <hr class="my-4">

    </div>
    <div class="col-lg-4 mt-4 mt-lg-0">
        {% include "passhint/site_detail_right_menu.html" %}
    </div>
</div>

<script>
    $(function () {
        $('#inline-pw-check').keyup(function (e) {
            var $form = $(this);
            
            if($form.find('#inline_pw_check')[0].value == '')
                return;

            var url = $form.attr('data-url');
            var data = $form.serialize();
            inline_pw_check(url, data, '{{LANGUAGE_CODE}}');
        });
    });
</script>

{% endblock passhint_content %}

passhint/templates/passhint/site_detail_right_menu.html
{% load i18n %}
<div>
    <h4 class="mb-3 px-2">
         {% trans "Information" %}
    </h4>
    <ul class="list-group mb-3">
        <li class="list-group-item">
            <div>
                <h6 class="my-0">{% trans "Site reporter" %}</h6>
                <strong>{{ site.user.username }}</strong>
                <span> at {{ site.created_at }}</span>
            </div>
        </li>
        <li class="list-group-item">
            <div>
                <h6 class="my-0">{% trans "passhint reporter" %}</h6>
                {% if site.get_recent_ruleset %}
                    <strong>{{ site.get_recent_ruleset.user.username }}</strong>
                    <span> at {{ site.get_recent_ruleset.created_at }}</span>
                {% else %}
                    <span class="text-primary">{% trans "Be the first passhinter!" %}</span>
                {% endif %}
            </div>
        </li>
        <li class="list-group-item">
            <div>
                <h6 class="my-0">{% trans "Hit" %}</h6>
                <span>{{ site.hit }}</span>
            </div>
        </li>
    </ul>
</div>

<div>
    <h4 class="mb-3 px-2">
        {% if site.get_recent_ruleset %}
            {% trans "Update passhint" %}
        {% else %}
            {% trans "Report passhint" %}
        {% endif %}
    </h4>
    <ul class="list-group mb-3">
        <li class="list-group-item">
            <div>
                {% if site.get_recent_ruleset %}
                    <h6 class="my-0">{% trans "Update passhint and get points!" %}</h6>
                {% else %}
                    {% trans "Be the first passhinter and get points!" %}
                {% endif %}
                <a class="btn btn-info btn-block mt-4" href="{% url "report:report_ruleset" site.name %}">{% trans "Report" %}</a>
            </div>
        </li>
    </ul>
</div>

<div>
    <ul class="list-group mt-4">
        <li class="list-group-item">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- block_ad -->
            <ins class="adsbygoogle"
                    style="display:block"
                    data-ad-client="ca-pub-6608881102769100"
                    data-ad-slot="4081090054"
                    data-ad-format="auto"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </li>
    </ul>
</div>

passhint/templates/passhint/site_search.html
{% extends "passhint/layout.html" %}
{% load i18n %}
{% load passhint_extras %}
{% block title %}{{keyword}} | Search | passhint{% endblock title %}
{% block passhint_content %}
{% get_current_language as LANGUAGE_CODE %}
{% if sites %} 
    {% for site in sites %}
    <div class="card mb-4">
        {% if forloop.counter|divisibleby:"6" %}
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <ins class="adsbygoogle"
                style="display:block"
                data-ad-format="fluid"
                data-ad-layout-key="-gw-3+1f-3d+2z"
                data-ad-client="ca-pub-6608881102769100"
                data-ad-slot="4353333048"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        {% else %}
            <div class="card-body p-3">
                <a href="{% url "passhint:site_detail" site.name %}">
                    <h4 class="card-title">{{ site.name }}</h4>
                </a>
                {% get_html_rule site.get_recent_ruleset.get_true_rule_list LANGUAGE_CODE %}
            </div>
        {% endif %}
    </div>
    {% endfor %} 
{% else %}
<div class="jumbotron text-center" style="background-color:#f8f9fa">
    <h1 class="display-4">{% trans "No Result Found" %}</h1>
    <hr class="my-4">
    <h5>{% trans "If you do not have the site you want, please report the site." %}</h5>
    <h5>{% trans "You can be the only reporter. And can get points!!" %}</h5>
    <a class="btn btn-secondary btn-lg mt-4" href="{% url "report:report_site" %}?name={{ keyword }}" role="button">{% trans "Report Site" %}</a>
</div>
{% endif %}
{% endblock passhint_content %}