accounts/urls.py
from django.conf import settings
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('social/signup/', views.MySignupView.as_view(), name='signup'),
]

api_v1/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'api_v1'
urlpatterns = [
    path('passhint/', views.passhint.as_view(), name='passhint'),
]

config/urls.py
from django.conf import settings
from django.shortcuts import redirect
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve

from passhint.views import main
from accounts.views import profile
from config.settings.base import get_secret

urlpatterns = [
    path('', main, name='main'),
    path('passhint/', include('passhint.urls')),
    path('report/', include('report.urls')),

    path('api_v1/', include('api_v1.urls')),
    
    path('profile/<str:username>/', profile, name='profile'),

    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path( get_secret("ADMIN_URL") +'/', admin.site.urls),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

passhint/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'passhint'
urlpatterns = [
    path('search/', views.site_search, name='site_search'),

    path('autocomplete/', views.autocomplete, name='autocomplete'),
    
    path('inline-pw-check/<str:site_name>/', views.inline_pw_check, name='inline_pw_check'),

    path('<str:site_name>/', views.site_detail, name='site_detail'),
]

report/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'report'
urlpatterns = [
    path('', views.report_site, name='report_site'),
    path('<str:site_name>/',
         views.report_ruleset, name='report_ruleset'),
]

config/templates/footer.html
<footer class="pt-4 my-5 pt-md-5 border-top text-muted text-center text-small">
    <p class="text-right">
        <a href="#">Back to top</a>
    </p>
    <p class="mb-1">
        <a href="mailto:kim.sardine@gmail.com" target="_top">kim.sardine@gmail.com</a>
         | &copy; passhint
    </p>
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="#">About</a>
        </li>
        <li class="list-inline-item">
            <a href="https://github.com/kim-sardine/passhint" target="_blank">Github</a>
        </li>
    </ul>
</footer>

config/templates/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <div class="container">
            <a class="navbar-brand" href="{% url "passhint:main" %}">passhint</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#my_navbar" aria-controls="my_navbar" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="my_navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {{ nav_site_search }}">
                        <a class="nav-link" href="{% url "passhint:site_search" %}">Site</a>
                    </li>
                    <li class="nav-item {{ nav_site_report }}">
                        <a class="nav-link" href="{% url "passhint:site_report" %}">Report</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Password</a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url "passhint:main" %}" class="form-inline my-2 my-lg-0 ml-lg-2" method="post">
                            {% csrf_token %}
                            <input type="text" name="site_name" class="form-control" id="search_name" placeholder="Search" aria-label="Search" maxlength="30"
                                required>
                            <button type="submit" class="my-button"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-1"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg></button>
                        </form>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <!--
                            TODO 로그인 안 한 상태에서는 로그인 버튼 보여주기
                        -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="my_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">IMG</a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="my_dropdown">
                            <a class="dropdown-item" href="#">Profile</a>
                            <a class="dropdown-item" href="#">Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

config/templates/layout.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Let's take the messy password rules in one shot.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta property="og:type" content="website" >
    <meta property="og:site_name" content="passhint" >
    <meta property="og:title" content="passhint" >
    <meta property="og:url" content="https://passhint.info/" >
    <meta property="og:description" content="Let's take the messy password rules in one shot." >
    <meta property="og:image" content="{% static "img/favicon.png" %}" >
    <title>{% block title %}passhint{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static "img/favicon.png" %}"/>
    <link href="{% static "css/style.css" %}" media="all" rel="Stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="{% static "assets/css/jquery-ui.css" %}" media="all" rel="Stylesheet" type="text/css" />
    <link href="{% static "assets/css/bootstrap.min.css" %}" media="all" rel="Stylesheet" type="text/css" />
    <script src="{% static "assets/js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "assets/js/jquery-ui.min.js" %}"></script>
    <script src="{% static "js/my_script.js" %}"></script>
</head>
<body>
    {% include "navbar.html" %}

    {% include "messages.html" %}

    {% block content %} {% endblock %}
    
    <link href="{% static "assets/css/bootstrap.min.css" %}" media="all" rel="Stylesheet" type="text/css" />
    <script src="{% static "assets/js/popper.min.js" %}"></script>
    <script src="{% static "assets/js/bootstrap.min.js" %}"></script>
</body>
</html>

config/templates/main_carousel.html
{% load static %}
{% load i18n %}
<div id="my_carousel" class="carousel slide border my-5" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#my_carousel" data-slide-to="0" class="active"></li>
        <li data-target="#my_carousel" data-slide-to="1"></li>
        <li data-target="#my_carousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static "img/main/rule_screenshot.png" %}" alt="Second slide">
                <div class="carousel-caption">
                    <h3 class="text-dark"><mark>{% trans "password rules are so different :(" %}</mark></h3>
                </div>
        </div>
        <div class="carousel-item active">
            <img class="d-block w-100" src="{% static "img/main/site_screen.png" %}" alt="First slide">
                <div class="carousel-caption">
                    <h3 class="text-dark"><mark>{% trans "browse all password rule here! :)" %}</mark></h3>
                </div>
        </div>
        <div class="carousel-item">
            <a class="nav-link" target="_blank" href="https://chrome.google.com/webstore/detail/passhint/dgeijdmkofncchjdjbihenbafdemcfbi">
                <img class="d-block w-100" src="{% static "img/main/google_screen.png" %}" alt="Third slide">
            </a>
                <div class="carousel-caption">
                    <h3 class="text-dark"><mark>{% trans "passhint for chrome extension is Super Coool!" %}</mark></h3>
                </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#my_carousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon bg-info" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#my_carousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon bg-info" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

config/templates/messages.html
<div class="container">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
</div>

config/templates/navbar.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <div class="container">
            {% if nav_main != 'active' %}
                <a class="navbar-brand" href="{% url "main" %}">passhint</a>
            {% endif %}
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#my_navbar" aria-controls="my_navbar" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="my_navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {{ nav_site_search }}">
                        <a class="nav-link" href="{% url "passhint:site_search" %}">Site</a>
                    </li>
                    <li class="nav-item {{ nav_report_site }}">
                        <a class="nav-link" href="{% url "report:report_site" %}">Report</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="https://chrome.google.com/webstore/detail/passhint/dgeijdmkofncchjdjbihenbafdemcfbi">Extension</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Password</a>
                    </li>
                    {% if nav_main != 'active' %}
                        <li class="nav-item">
                            <form action="{% url "main" %}" class="form-inline my-2 my-lg-0 ml-lg-2" method="post">
                                {% csrf_token %}
                                <input type="text" name="keyword" class="form-control" id="search_name" placeholder="Search" aria-label="Search" maxlength="30"
                                    required>
                                <button type="submit" class="my-button"><i class="material-icons" style="line-height: unset;">search</i></button>
                            </form>
                        </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="my_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons" style="vertical-align: top;">person</i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="my_dropdown">
                                <a class="dropdown-item nav-link" href="{% url "profile" user.username %}">Profile</a>
                                <a class="dropdown-item nav-link" href="{% url "accounts:logout" %}">Logout</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav">
                        <li>
                            <a class="dropdown-item nav-link" href="{% url "accounts:login" %}">Login</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
</header>